GET http://localhost:4000/countries HTTP/1.1

###

GET http://localhost:4000/empty HTTP/1.1

###

GET http://localhost:4000/films HTTP/1.1

###

GET http://localhost:4000/workflow-docs/workflows HTTP/1.1

###

GET http://localhost:4000/workflow-docs/workflow-doc?path=/Users/marco/open-source/nanoservice-ts/triggers/http/workflows/json/countries.json HTTP/1.1